#
warnings_are_errors: false

language: r

matrix:
  include:
  - os: linux
    r: release
  - os: osx
    r: release

branches:
  only:
  - master

sudo: false

cache: packages

notifications:
  email:
    on_success: change
    on_failure: change
    
deploy:
  provider: releases
  api_key:
    secure: hd/AVHdIxPFEYvx66wCgXHfm0mFr/SGgiwRks8q9vSVHZwTrKoOyutt80p5lbPLSOaLIb818ZBAaxYuaKACoxZWblS/Rm+VfR3q/ct+y5Mx9EUQItuHTWbD/Y7wwcoa9myvh45U72ubve+UWbBjJUDNYrGrlX/OaJcIMu8QfGx4=
  skip_cleanup: true
  file_glob: true
  file: FLCore_*.tgz
  file: FLCore_*.tar.gz
  on:
    os: osx
    branch: master
    repo: flr/FLCore
    tags: true
