# Sample .travis.yml for R projects.
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
# https://github.com/craigcitro/r-travis/wiki

os:
  - linux
  - osx

language: R
  
sudo: required
